on:
  push:
    paths-ignore: # do not execute actions when there are only changes to README and .gitignore
      - 'README.md'
      - '.gitignore'
name: Flutter CI ## this is the name of the workflow
jobs:
  build: ## this workflow has one job which is labelled build (i don't think this name matters but don't quote me)
    name: install dependencies
    runs-on: ubuntu-latest ## this workflow is run on a ubuntu machine located at some github office
    steps:

    - uses: actions/checkout@v1
    - name: decrypt secret
      run: ./.github/scripts/decrypt_secret.sh
      env:
        PASSPHRASE: ${{ secrets.PASSPHRASE }}

    - uses: actions/checkout@v1 ## this is a github action used to have access to, and traverse our repo's directories
    - name: install dependencies
      uses: steebchen/flutter@v1.0.0 ## this is a github action used to actually install all of the flutter prerequisites needed to build the app
      with:
        args: pub get ## run 'flutter pub get'

    # - name: run tests
    #   uses: steebchen/flutter@v1.0.0
    #   with:
    #     args: test ## runs 'flutter test' (this is where we would run the files in test directory)

    - name: build apk
      uses: steebchen/flutter@v1.0.0
      with:
        args: build apk --release ## runs 'flutter build apk --release'